services:
  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"

  rxapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_CONNECTION_STRING=Host=host.docker.internal;Database=astro;Username=postgres;Password=aleksa
    ports:
      - "80"