apiVersion: v1
kind: Service
metadata:
  name: rxapi
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: rxapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rxapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rxapi
  template:
    metadata:
      labels:
        app: rxapi
    spec:
      containers:
      - name: isinrx-rxapi
        image: aleksamagicka/rxapi:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: db-credentials